### ISSUE TITLE
Make the project have continuous integration.

### ISSUE THREAD

**Issue by martinreycristina** [Arquisoft/dechat_es5b#29]
In order for it to have continuous integration, we will have to modify the packages.json and .travis.yml files of the project.
It is preferable to change the packages.json file using npm commands rather than manually.

**Comment by mesacarlos** [comment]
Opened features/travis branch to work around this issue

**Comment by martinreycristina** [comment]
I had already opened a branch for this purpose. It's called features/continuous-integration.

**Comment by mesacarlos** [comment]
Didn't notice the existence of that branch..
Merging travis to continuous-integration

**Comment by mesacarlos** [comment]
Solved
