### ISSUE TITLE
Prototype cli chat

### ISSUE THREAD

**Issue by DiegoFernMart** [Arquisoft/dechat_es5b#30]
Working at cli chat prototype based on solid chess.
Base files uploaded to branch feature/cli
defining semanticChat class for store chat info

Status: Not finished

**Comment by DiegoFernMart** [comment]
Trying new version in Node.js, using [solid-file-client](https://github.com/jeff-zucker/solid-file-client) lib.

**Comment by mesacarlos** [comment]
Branch and files deleted. Group decided not to use CLI-based chat
