### ISSUE TITLE
Send msg Notification

### ISSUE THREAD

**Issue by DiegoFernMart** [Arquisoft/dechat_es5b#46]
Create notification for new msg in receiver POD.
Show them in a visible area of the app

**Comment by mesacarlos** [comment]
(Only UI Team) Bootstrap supports Toasts, which are a fancy way to show notifications to users. Refer to https://getbootstrap.com/docs/4.2/components/toasts/

(Backend Team) Also, Modern web browsers support JS Notifications API which sends a notifications to the browser, showing it in system's notification bar. Refer to https://developer.mozilla.org/es/docs/Web/API/notification

**Comment by DiegoFernMart** [comment]
Disabled Notification System.
Encountered potential error, Error 403(Forbidden) - Related: https://github.com/jeff-zucker/solid-file-client/issues/28
