### ISSUE TITLE
Trying to order the friend list

### ISSUE THREAD

**Issue by UO253374** [Arquisoft/dechat_es5b#97]
I was trying to order the friend list but I don't know If this is the correct place to put it.

main.js
```
//Display their friends
const friends = store.each($rdf.sym(chatM.INFO.user), FOAF('knows'));
$('#friends').empty();

```
**Like this?**

	friends.sort(function(a, b) {
		var n = a.chatM.INFO.userName.toLocaleLowerCase().localeCompare(b.chatM.INFO.userName.toLocaleLowerCase());
		return n === 0 && a.chatM.INFO.userName !== b.chatM.INFO.userName ? b.chatM.INFO.userName.localeCompare(a.chatM.INFO.userName) : n;
	  }); 

**Or this?**

	friends.sort((a, b) => new Date(a.lastmessage) > new Date(b.lastmessage)); 
****
	friends.forEach(
		async (friend) => {
			await fetcher.load(friend);
			$('#friends').append(
				$('<button>').attr('type', 'button').addClass("list-group-item list-group-item-action noactive").text(store.any(friend, FOAF('name'))).click(
					async function () {
						if (chatM.ToLog)
							console.log("load new receiver");
						//Store all reciever info need for future
						chatM.INFO.receiver = friend.value;
						chatM.INFO.receiverName = store.any(friend, FOAF('name')).toString().trim();
						chatM.INFO.receiverURI = chatM.INFO.receiver.substr(0, (chatM.INFO.receiver.length - 15));

I'm not sure about how to access the info of the friend userName or the list of messages each person have with each friend

**Comment by UO253374** [comment]
Also, I don't know why but my friend list does not appear in my de-chat

**Comment by martinreycristina** [comment]
I think it would be better to list friends by the date of the last message and also add a search engine to find those we do not have recent.

**Comment by martinreycristina** [comment]
To access the name of the friend you are chatting with you can use the "receiverName" attribute described in the "INFO" object of "ChatManager".
`chatM.INFO.receiverName`
For messages with a specific friend you must do the same but with the attribute "toShow" and the object "MESSAGES", also from "ChatManager".
`chatM.MESSAGES.toShow`
You must access these attributes as long as they have already been initialized. That is to say, once the friends list has been loaded or once the conversation with a friend has been loaded. If you need to do it before, tell me.

**Comment by martinreycristina** [comment]
> Also, I don't know why but my friend list does not appear in my de-chat

This may be because you're using the first comparison function to sort the list of friends, when I use that function it doesn't show them to me either. 
And for the second one, the lastMessage attribute must be added to friends if it hasn't already been added.

**Comment by martinreycristina** [comment]
I have finally decided to put them in alphabetical order for simplicity.
It can be changed in the future.
